language: python
cache: pip

sudo: false

python:
  - 3.5
install:
  - pip install -r requirements/dev.txt
  - pip install coveralls
script:
  - coverage run manage.py test
  - flake8 .
after_success:
  - coveralls
