version: '2'

services:
  postgres:
    image: postgres:9.5.4
    restart: always
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: wagtail
      POSTGRES_DB: wagtail
      PGDATA: /var/lib/postgresql/data/pgdata

  wagtail:
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ".:/usr/src/app"
    environment:
      DB_HOST: postgres
      DB_USER: wagtail
      DB_PASSWORD: wagtail

volumes:
  postgres-db-volume:
    driver: local
