version: '2'

services:
  db:
    image: postgres:9.5.4
    restart: always
    environment:
      POSTGRES_USER: nhsuk
      POSTGRES_PASSWORD: nhsuk
      POSTGRES_DB: nhsuk
      PGDATA: /var/lib/postgresql/data/pgdata

  content-store:
    build: .
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ".:/usr/src/app"
    environment:
      DB_HOST: db
      DB_USER: nhsuk
      DB_PASSWORD: nhsuk
